

// Default Connect Module setup
ams_cm  mode=split vsup=3.3 crules=crules;
ams_set_discipline discipline=logic;

//Example on how to set the discipline on a digital cell/hierarchy, where there are physical power pins VDD/VSS
ams_set_discipline discipline=logic      cell=dig_top;
ams_set_discipline discipline=electrical cell=dig_top node=VDD;
ams_set_discipline discipline=electrical cell=dig_top node=VSS;

//Setup the commands to handle inherited connect attributes.
//cm_net is internal net name, default_supply sets default value for SNPS attributes, inherited_supply set the default to the CDNS inherted property names. 
ams_cdef_net_cm -lib WORK -cell l2e   -cm_net { vdd } -default_supply { snps_cm_power  => cds_globals.\\gnd!  } -inherited_supply { dig_vdd => cds_globals.\\gnd!  };
ams_cdef_net_cm -lib WORK -cell l2e   -cm_net { vss } -default_supply { snps_cm_ground => cds_globals.\\gnd!  } -inherited_supply { dig_vss => cds_globals.\\gnd!  };

ams_cdef_net_cm -lib WORK -cell e2l   -cm_net { vdd } -default_supply { snps_cm_power  => cds_globals.\\gnd!  } -inherited_supply { dig_vdd => cds_globals.\\gnd!  };
ams_cdef_net_cm -lib WORK -cell e2l   -cm_net { vss } -default_supply { snps_cm_ground => cds_globals.\\gnd!  } -inherited_supply { dig_vss => cds_globals.\\gnd!  };

ams_cdef_net_cm -lib WORK -cell bidir -cm_net { vdd } -default_supply { snps_cm_power  => cds_globals.\\gnd!  } -inherited_supply { dig_vdd => cds_globals.\\gnd!  };
ams_cdef_net_cm -lib WORK -cell bidir -cm_net { vss } -default_supply { snps_cm_ground => cds_globals.\\gnd!  } -inherited_supply { dig_vss => cds_globals.\\gnd!  };
