//###############################################################################################
// 
// MIT No Attribution
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify,
// merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
// PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// 
//###############################################################################################

//These should be added to the main vcsAD.init file
// Default Connect Module setup
ams_cm  mode=split vsup=3.3 crules=crules;
ams_set_discipline discipline=logic;

//Example on how to set the discipline on a digital cell/hierarchy, where there are physical power pins VDD/VSS
ams_set_discipline discipline=logic      cell=dig_top;
ams_set_discipline discipline=electrical cell=dig_top node=VDD;
ams_set_discipline discipline=electrical cell=dig_top node=VSS;

//Setup the commands to handle inherited connect attributes.
//cm_net is internal net name, default_supply sets default value for SNPS attributes, inherited_supply sets the default to the CDNS inherted property names. 
ams_cdef_net_cm -lib WORK -cell l2e   -cm_net { vdd } -default_supply { snps_cm_power  => snps_globals.\\gnd!  } -inherited_supply { vdd => snps_globals.\\gnd!  };
ams_cdef_net_cm -lib WORK -cell l2e   -cm_net { vss } -default_supply { snps_cm_ground => snps_globals.\\gnd!  } -inherited_supply { vss => snps_globals.\\gnd!  };

ams_cdef_net_cm -lib WORK -cell e2l   -cm_net { vdd } -default_supply { snps_cm_power  => snps_globals.\\gnd!  } -inherited_supply { vdd => snps_globals.\\gnd!  };
ams_cdef_net_cm -lib WORK -cell e2l   -cm_net { vss } -default_supply { snps_cm_ground => snps_globals.\\gnd!  } -inherited_supply { vss => snps_globals.\\gnd!  };

ams_cdef_net_cm -lib WORK -cell bidir -cm_net { vdd } -default_supply { snps_cm_power  => snps_globals.\\gnd!  } -inherited_supply { vdd => snps_globals.\\gnd!  };
ams_cdef_net_cm -lib WORK -cell bidir -cm_net { vss } -default_supply { snps_cm_ground => snps_globals.\\gnd!  } -inherited_supply { vss => snps_globals.\\gnd!  };
